/**
 * Regenerate `src/app/routeTree.gen.ts` from `src/app/routes.ts`.
 *
 * The Vite plugin is supposed to do this on every build and does not: given a
 * new entry in `routes.ts` and its route file present, `vite build` reproduces
 * the previous route set exactly — for any file name, any file content, and
 * even after deleting the generated tree so it must rebuild from scratch. The
 * plugin is genuinely active (point `routesDirectory` at a missing directory
 * and the build fails with its error), and it is reading the virtual config
 * (it knows the root route is `root.tsx`, which only `routes.ts` says), so the
 * fault is somewhere between the plugin and the generator it bundles.
 *
 * The generator itself is fine. Driven directly with a parsed config it emits
 * the new route immediately, which is what this script does. Run it after
 * editing `routes.ts`, and commit the regenerated tree — it is a tracked file.
 *
 *   pnpm gen:routes
 *
 * Delete this script the day a plugin upgrade makes it redundant; the check at
 * the end of `pnpm ci`-style runs is `git diff --exit-code src/app/routeTree.gen.ts`
 * after running it.
 */
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const web = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(`${web}/package.json`);

// Resolved through the plugin, which pins the generator version it bundles —
// so this script cannot drift onto a different generator than the build uses.
const generatorEntry = require.resolve("@tanstack/router-generator", {
  paths: [require.resolve("@tanstack/router-plugin")],
});

const { Generator, getConfig } = await import(generatorEntry);

const config = getConfig(
  {
    target: "react",
    routesDirectory: "./src/app/routes",
    generatedRouteTree: "./src/app/routeTree.gen.ts",
    virtualRouteConfig: "./src/app/routes.ts",
    quoteStyle: "double",
    semicolons: true,
    routeTreeFileHeader: [
      "// biome-ignore-all lint: generated by TanStack Router",
    ],
  },
  web,
);

await new Generator({ config, root: web }).run();
console.log("routeTree.gen.ts regenerated from routes.ts");
