// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as reposRouteImport } from "./routes/repos";
import { Route as indexRouteImport } from "./routes/index";
import { Route as reposDotsettingsRouteImport } from "./routes/repos.settings";
import { Route as reposDotbrowseRouteImport } from "./routes/repos.browse";
import { Route as reposDotagentsRouteImport } from "./routes/repos.agents";
import { Route as reposDotrepoIdRouteImport } from "./routes/repos.$repoId";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as reposDotrepoIdDotblobDotsplatRouteImport } from "./routes/repos.$repoId.blob.$";

const reposRoute = reposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotsettingsRoute = reposDotsettingsRouteImport.update({
  id: "/repos/settings",
  path: "/repos/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotbrowseRoute = reposDotbrowseRouteImport.update({
  id: "/repos/browse",
  path: "/repos/browse",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotagentsRoute = reposDotagentsRouteImport.update({
  id: "/repos/agents",
  path: "/repos/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdRoute = reposDotrepoIdRouteImport.update({
  id: "/repos/$repoId",
  path: "/repos/$repoId",
  getParentRoute: () => rootRouteImport,
} as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdDotblobDotsplatRoute =
  reposDotrepoIdDotblobDotsplatRouteImport.update({
    id: "/repos/$repoId/blob/$",
    path: "/repos/$repoId/blob/$",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/repos": typeof reposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/agents": typeof reposDotagentsRoute;
  "/repos/browse": typeof reposDotbrowseRoute;
  "/repos/settings": typeof reposDotsettingsRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/repos": typeof reposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/agents": typeof reposDotagentsRoute;
  "/repos/browse": typeof reposDotbrowseRoute;
  "/repos/settings": typeof reposDotsettingsRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/repos": typeof reposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/agents": typeof reposDotagentsRoute;
  "/repos/browse": typeof reposDotbrowseRoute;
  "/repos/settings": typeof reposDotsettingsRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/agents"
    | "/repos/browse"
    | "/repos/settings"
    | "/repos/$repoId/blob/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/agents"
    | "/repos/browse"
    | "/repos/settings"
    | "/repos/$repoId/blob/$";
  id:
    | "__root__"
    | "/"
    | "/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/agents"
    | "/repos/browse"
    | "/repos/settings"
    | "/repos/$repoId/blob/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  reposRoute: typeof reposRoute;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
  reposDotrepoIdRoute: typeof reposDotrepoIdRoute;
  reposDotagentsRoute: typeof reposDotagentsRoute;
  reposDotbrowseRoute: typeof reposDotbrowseRoute;
  reposDotsettingsRoute: typeof reposDotsettingsRoute;
  reposDotrepoIdDotblobDotsplatRoute: typeof reposDotrepoIdDotblobDotsplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/repos": {
      id: "/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof reposRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/settings": {
      id: "/repos/settings";
      path: "/repos/settings";
      fullPath: "/repos/settings";
      preLoaderRoute: typeof reposDotsettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/browse": {
      id: "/repos/browse";
      path: "/repos/browse";
      fullPath: "/repos/browse";
      preLoaderRoute: typeof reposDotbrowseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/agents": {
      id: "/repos/agents";
      path: "/repos/agents";
      fullPath: "/repos/agents";
      preLoaderRoute: typeof reposDotagentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId": {
      id: "/repos/$repoId";
      path: "/repos/$repoId";
      fullPath: "/repos/$repoId";
      preLoaderRoute: typeof reposDotrepoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId/blob/$": {
      id: "/repos/$repoId/blob/$";
      path: "/repos/$repoId/blob/$";
      fullPath: "/repos/$repoId/blob/$";
      preLoaderRoute: typeof reposDotrepoIdDotblobDotsplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  reposRoute: reposRoute,
  inviteDotcodeRoute: inviteDotcodeRoute,
  reposDotrepoIdRoute: reposDotrepoIdRoute,
  reposDotagentsRoute: reposDotagentsRoute,
  reposDotbrowseRoute: reposDotbrowseRoute,
  reposDotsettingsRoute: reposDotsettingsRoute,
  reposDotrepoIdDotblobDotsplatRoute: reposDotrepoIdDotblobDotsplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
