import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    tanstackRouter({
      target: "react",
      // Generation is done by `pnpm gen:routes`, not here. The plugin is
      // active and reads this config, but silently reproduces the previous
      // route set: a new entry in routes.ts never reaches routeTree.gen.ts,
      // and a build would overwrite a correctly generated tree with the stale
      // one. The generator itself is fine when driven directly, which is what
      // scripts/gen-routes.mjs does. The plugin is kept for code-splitting and
      // HMR. See scripts/gen-routes.mjs.
      enableRouteGeneration: false,
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
    },
  },
  server: {
    port: parseInt(process.env.VITE_PORT || "5173", 10),
    strictPort: true,
  },
});
