import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    tanstackRouter({
      target: "react",
      // Generation is done by `pnpm gen:routes`, not here. The plugin is
      // active and reads this config, but silently reproduces the previous
      // route set: a new entry in routes.ts never reaches routeTree.gen.ts,
      // and a build would overwrite a correctly generated tree with the stale
      // one. The generator itself is fine when driven directly, which is what
      // scripts/gen-routes.mjs does. The plugin is kept for code-splitting and
      // HMR. See scripts/gen-routes.mjs.
      enableRouteGeneration: false,
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
    },
  },
  server: {
    port: parseInt(process.env.VITE_PORT || "5173", 10),
    strictPort: true,
  },
  // `vite preview` is what the Playwright suite runs against, so it answers
  // like the relay does in production: the service worker script lives in
  // /assets/ but registers at root scope, which the browser only allows when
  // the script response carries this header (crates/buzz-relay/src/router.rs).
  // Without it every signed-out page logs a scope error the relay never
  // produces, and the smoke specs' zero-console-error checks fail on the
  // harness rather than the app.
  preview: {
    headers: { "Service-Worker-Allowed": "/" },
  },
});
